title: oh my polo! # name of the site
author: Roman Lesechko # name of site's author
email:  not@now.xx # email of site's author
url: https://polo7.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  software development, project management
permalink: /:slug.html

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# Theme settings
# theme: minima # default jekyll theme
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  back_prev_page_text: "back"
  
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
